### PR TITLE
Change Play-DL library, update libraries and improve error handling

### LINKED ISSUE #26: Broken Discord music player
### Problem statement
The music-playing functionality is currently broken on Play-DL due to a change in YouTube. [Issue link](https://github.com/play-dl/play-dl/issues/370)

### Temporary Solution
[A fork](https://github.com/Yoduh/play-dl-test) utilizing an iOS extractor has been made available as a temporary fix.

### LINKED ISSUE #27: Bot crash if user is not in voice channel
### Problem statement
The Discord bot crashes if the user requesting music using the `!play` command is not inside a voice channel. Proper error handling is required.

### PR DESCRIPTION
**Pull request by Lucas7781**
Fix and stabilize music playing of the discord bot
1. Update the play-dl library to a fork fixing the player. 
2. Fixed error handling for playing music while not in a voice channel. 
3. Updated libraries.

### CODE REVIEW

File: commands.js [hunk 1]
```diff
@@ -11,7 +11,9 @@ function play(client, message) {
   }
   try{
     let input = message.content.split(' ');input.shift(); input = input.join(' ')
-    client.botMap.get(message.guild.id).musicBot.play(message.channel, message.member.voice.channel, input)
+    client.botMap.get(message.guild.id).musicBot.play(message.channel, message.member.voice.channel, input).catch(err =>
+      console.log(err)
```
Comment (Matei9721) [inline commands.js]: Better to log it to the error files than printing it for the hosted version.

File: commands/play.js [hunk 2]
```diff
@@ -28,7 +28,9 @@ module.exports = {
             const input = interaction.options.get("song").value
             const bot = client.botMap.get(interaction.guild.id)
             const voiceChannel = interaction.member.voice.channel
-            await bot.musicBot.play(interaction.channel, voiceChannel, input);
+            await bot.musicBot.play(interaction.channel, voiceChannel, input).catch(err =>{
+                console.error(err)
```
Comment (Matei9721) [inline commands/play.js]: Same as above.

**Review by Matei9721 — CHANGES_REQUESTED** [review]

**Review by Matei9721 — APPROVED** [review]
Looks good to me
